- name: Create ZooKeeper systemd service unit file
  become: true
  template:
    src: zookeeper.service.j2
    dest: /etc/systemd/system/zookeeper.service
    owner: ec2-user
    group: ec2-user
    mode: '0644'

- name: Reload systemd daemon
  become: true
  systemd:
    daemon_reload: yes

- name: Enable ZooKeeper to start on boot
  become: true
  systemd:
    name: zookeeper
    enabled: yes

- name: Start ZooKeeper via systemd
  become: true
  systemd:
    name: zookeeper
    state: started
