# kafka/main.yml (Install Phase)
- name: Download Kafka
  get_url:
    url: https://archive.apache.org/dist/kafka/3.6.1/kafka_2.13-3.6.1.tgz
    dest: /tmp/kafka.tgz

- name: Extract Kafka
  unarchive:
    src: /tmp/kafka.tgz
    dest: /opt/
    remote_src: yes

- name: Remove existing /opt/kafka directory if it exists
  file:
    path: /opt/kafka
    state: absent
  when:
    - ansible_facts['devices'] is defined  
    - ansible_facts['distribution'] is defined
    - 
- name: Create symbolic link to /opt/kafka
  file:
    src: /opt/kafka_2.13-3.6.1
    dest: /opt/kafka
    state: link

- name: Ensure Kafka base directory is owned by ec2-user
  file:
    path: /opt/kafka
    state: directory
    recurse: yes
    owner: ec2-user
    group: ec2-user
    mode: '0755'

- name: Clean Kafka logs and data directories
  file:
    path: "{{ item }}"
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: '0755'
    recurse: yes
  loop:
    - /tmp/kafka-logs
    - /tmp/kraft-combined-logs

- name: Copy server.properties
  template:
    src: server.properties.j2
    dest: "{{ kafka_home }}/config/server.properties"
    owner: ec2-user
    group: ec2-user
    mode: '0644'

- name: Debug private IP
  debug:
    msg: "Private IP for {{ inventory_hostname }} is {{ hostvars[inventory_hostname].private_ip }}"

- name: Fail if private_ip is not defined
  fail:
    msg: "Private IP not found for {{ inventory_hostname }}"
  when: hostvars[inventory_hostname].private_ip is not defined

