- name: Create Kafka systemd service unit file
  become: true
  template:
    src: kafka.service.j2
    dest: /etc/systemd/system/kafka.service
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd daemon
  become: true
  systemd:
    daemon_reload: yes

- name: Enable Kafka to start on boot
  become: true
  systemd:
    name: kafka
    enabled: yes

- name: Debug rendered kafka.service path
  command: cat /etc/systemd/system/kafka.service
  register: kafka_unit
  become: true

- debug:
    var: kafka_unit.stdout_lines