- name: Create Kafka systemd service unit file
  become: true
  template:
    src: kafka.service.j2
    dest: /etc/systemd/system/kafka.service
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd daemon
  become: true
  systemd:
    daemon_reload: yes

- name: Enable Kafka to start on boot
  become: true
  systemd:
    name: kafka
    enabled: yes

- name: Start Kafka via systemd
  become: true
  systemd:
    name: kafka
    state: started
