- name: Wait for ZooKeeper to be up (self)
  wait_for:
    host: "{{ hostvars[inventory_hostname].private_ip }}"
    port: 2181
    state: started
    delay: 5
    timeout: 60

- name: Wait for ZooKeeper peers to be up
  wait_for:
    host: "{{ hostvars[item].private_ip }}"
    port: 2181
    state: started
    timeout: 60
  loop: "{{ groups['all'] | difference([inventory_hostname]) }}"
  when: hostvars[item].private_ip is defined
  delegate_to: localhost
  become: false

- name: Configure Kafka systemd unit
  template:
    src: kafka.service.j2
    dest: /etc/systemd/system/kafka.service
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd to pick up Kafka service
  systemd:
    daemon_reload: yes

- name: Enable Kafka service on boot
  systemd:
    name: kafka
    enabled: yes

- name: Start Kafka broker
  systemd:
    name: kafka
    state: started

- name: Wait for Kafka broker to be up
  wait_for:
    host: "{{ hostvars[inventory_hostname].private_ip }}"
    port: 9092
    state: started
    delay: 5
    timeout: 90
