---
- name: Install Amazon Corretto Java 11
  block:
    - name: Add Amazon Corretto 11 YUM repo
      get_url:
        url: https://corretto.aws/downloads/latest/amazon-corretto-11-x64-linux-jdk.rpm
        dest: /tmp/amazon-corretto-11.rpm

    - name: Install Amazon Corretto 11 from RPM
      yum:
        name: /tmp/amazon-corretto-11.rpm
        state: present

    - name: Verify Java installation
      command: java -version
      register: java_version_output
      changed_when: false

    - name: Print Java version
      debug:
        var: java_version_output.stdout_lines
